# Name of the package if any. Package.ModuleName will be the module name 
package_name = ""

# The documentation string of the module. 
documentation = ""

# Namespace. 
# Only the classes/functions/enums declared in this namespace will be wrapped
namespace = ""

# Match/reject elements according to regex
# If match_names/match_names are both set, filter for all elements 
# Algorithm is (for an element X of fully qualified name Qname)
#    if match_names and not match_names match Qname : skip X
#    if reject_names and reject_names match Qname : skip X
#    else keep X.

# match_names = ""
# reject_names = ""

# Only keep elements declared in files matching the pattern
# match_files = "" # String must be a regex
