#include "./wdata.hpp"
#include "clu/fullqualifiedname.hpp"
#include "tools/ir/types.hpp"
#include "utility/logger.hpp"

#include <clang/AST/DeclCXX.h>
#include <filesystem>
#include <fstream>

// ------------------------------

// Parse one line of a .wrap.hxx file and return the type name inside
//   template <> constexpr bool c2py::is_wrapped<TYPE> = true;
// Returns empty string on no match.
static std::string extract_is_wrapped_type(std::string const &line) {
  static constexpr std::string_view prefix = "c2py::is_wrapped<";
  auto start = line.find(prefix);
  if (start == std::string::npos) return {};
  start += prefix.size();
  auto eq = line.find("= true", start);
  if (eq == std::string::npos) return {};
  auto close = line.rfind('>', eq);
  if (close == std::string::npos || close < start) return {};
  return util::trim(line.substr(start, close - start));
}

// ------------------------------

void wdata_t::add_class_to_module(std::string_view name, clang::CXXRecordDecl const *cls) {
  module_info.add_class(name, ir::RecordDecl{*cls});
}

bool wdata_t::is_wrapped_in_module(clang::QualType ty) const {
  clang::CXXRecordDecl const *cls = ty->getAsCXXRecordDecl();
  if (!cls) cls = ty->getPointeeCXXRecordDecl();
  if (!cls) return false;
  auto fqn = clu::get_fully_qualified_name(cls->getCanonicalDecl());
  return module_info.is_wrapped(fqn);
}

// ------------------------------

wdata_t::wdata_t(clang::CompilerInstance *ci, configuration const &config) : ci{ci}, config{config} {

  auto p                           = std::filesystem::absolute(ci->getFrontendOpts().Inputs[0].getFile().str());
  module_info.sourcefile           = str_t{p.string()};
  module_info.module_name          = str_t{p.stem()};
  module_info.sourcefile_full_stem = p.parent_path() / p.stem();
  module_info.package_name         = config.package_name;
  module_info.documentation        = config.documentation;

  util::logger::set_log(module_info.sourcefile_full_stem + ".log");

  if (not config.reject_names.empty()) this->reject_names = llvm::Regex(config.reject_names);

  // Scan .wrap.hxx files in the source directory to build the type -> header table.
  // Each .wrap.hxx generated by clair for another module contains a line like:
  //   template <> constexpr bool c2py::is_wrapped<my_ns::Foo> = true;
  std::error_code ec;
  for (auto const &entry : std::filesystem::directory_iterator(p.parent_path(), ec)) {
    if (!entry.path().string().ends_with(".wrap.hxx")) continue;
    std::ifstream hf(entry.path());
    std::string line;
    while (std::getline(hf, line)) {
      if (auto type_name = extract_is_wrapped_type(line); !type_name.empty())
        wrapped_type_to_header.emplace(std::move(type_name), entry.path().filename().string());
    }
  }
}
