#include "./wdata.hpp"

#include <filesystem>
#include <fstream>
#include "llvm/ADT/DenseSet.h"
#include "utility/logger.hpp"

// ------------------------------

// Among all redeclarations of f, pick the best one:
// 1. Prefer a redecl with default arguments (at most one exists per C++ rules)
// 2. Otherwise prefer a redecl where all parameters are named
// 3. Fall back to the most recent redecl
static const clang::FunctionDecl *best_redecl(const clang::FunctionDecl *f) {
  const clang::FunctionDecl *with_names = nullptr;
  for (auto *redecl : f->redecls()) {
    auto *r = llvm::dyn_cast<clang::FunctionDecl>(redecl);
    if (not r) continue;
    if (llvm::any_of(r->parameters(), [](auto *p) { return p->hasDefaultArg(); })) return r;
    if (not with_names and llvm::all_of(r->parameters(), [](auto *p) { return !p->getName().empty(); })) with_names = r;
  }
  return with_names ? with_names : f->getMostRecentDecl();
}

// ------------------------------

std::vector<fnt_info_t> make_unique_decls(std::vector<fnt_info_t> const &flist) {
  llvm::DenseSet<const clang::FunctionDecl *> seen; // LLVM recommended replacement of std::set
  std::vector<fnt_info_t> res;
  seen.reserve(flist.size());
  res.reserve(flist.size());

  for (const auto &f : flist) {
    if (seen.insert(f.ptr->getMostRecentDecl()).second) {
      auto *best = best_redecl(f.ptr);
      res.push_back({.ptr = best, .rewrite = f.rewrite, .parent_class = f.parent_class});
    }
  }

  return res;
}

// ------------------------------

// Parse one line of a .wrap.hxx file and return the type name inside
//   template <> constexpr bool c2py::is_wrapped<TYPE> = true;
// Returns empty string on no match.
static std::string extract_is_wrapped_type(std::string const &line) {
  static constexpr std::string_view prefix = "c2py::is_wrapped<";
  auto start = line.find(prefix);
  if (start == std::string::npos) return {};
  start += prefix.size();
  auto eq = line.find("= true", start);
  if (eq == std::string::npos) return {};
  auto close = line.rfind('>', eq);
  if (close == std::string::npos || close < start) return {};
  return util::trim(line.substr(start, close - start));
}

// ------------------------------

void module_info_t::add_class(std::string_view name, clang::CXXRecordDecl const *cls) {
  auto *key = cls->getCanonicalDecl();
  if (classes_ptr_to_info.contains(key)) return; // already registered
  classes.emplace_back(name, cls_info_t{.ptr = cls});
  classes_ptr_to_info[key] = long(classes.size() - 1);
}

// ------------------------------

cls_ptr_t module_info_t::get_wrapped_cls(clang::QualType ty) const {
  clang::CXXRecordDecl const *cls = ty->getAsCXXRecordDecl();
  if (!cls) cls = ty->getPointeeCXXRecordDecl();
  if (cls) cls = cls->getCanonicalDecl();
  return (cls and classes_ptr_to_info.contains(cls)) ? cls : nullptr;
}

// ------------------------------

cls_info_t *module_info_t::get_wrapped_cls_info(clang::QualType ty) {
  auto cls = get_wrapped_cls(ty);
  return cls ? &classes[classes_ptr_to_info.at(cls)].second : nullptr;
}

// ------------------------------

bool module_info_t::is_wrapped(clang::QualType ty) const { return get_wrapped_cls(ty) != nullptr; }

// ------------------------------

wdata_t::wdata_t(clang::CompilerInstance *ci, configuration const &config) : ci{ci}, config{config} {

  auto p                           = std::filesystem::absolute(ci->getFrontendOpts().Inputs[0].getFile().str());
  module_info.sourcefile           = str_t{p.string()};
  module_info.module_name          = str_t{p.stem()};
  module_info.sourcefile_full_stem = p.parent_path() / p.stem();
  module_info.package_name         = config.package_name;
  module_info.documentation        = config.documentation;

  util::logger::set_log(module_info.sourcefile_full_stem + ".log");

  // Validity of the regex is checked in the configuration constructor
  if (not config.reject_names.empty()) this->reject_names = llvm::Regex(config.reject_names);

  // Scan .wrap.hxx files in the source directory to build the type -> header table.
  // Each .wrap.hxx generated by clair for another module contains a line like:
  //   template <> constexpr bool c2py::is_wrapped<my_ns::Foo> = true;
  std::error_code ec;
  for (auto const &entry : std::filesystem::directory_iterator(p.parent_path(), ec)) {
    if (!entry.path().string().ends_with(".wrap.hxx")) continue;
    std::ifstream hf(entry.path());
    std::string line;
    while (std::getline(hf, line)) {
      if (auto type_name = extract_is_wrapped_type(line); !type_name.empty())
        wrapped_type_to_header.emplace(std::move(type_name), entry.path().filename().string());
    }
  }
}
